# Generated by Django 5.1.2 on 2024-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loingdata',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medicaldata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('lno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='medicinedata',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=100)),
                ('lno', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('med_type', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('email_of_medical', models.CharField(max_length=100)),
            ],
        ),
    ]
